### ISSUE TITLE
image do not exist

### ISSUE THREAD

**Issue by somedevreally** [dstubbs95/docker-youtube-dlg#1]
Unable to find image 'docker-youtube-dlg:latest' 
docker: Error response from daemon: pull access denied for docker-youtube-dlg, repository does not exist or may require 'docker login'.

**Comment by dstubbs95** [comment]
Can you please give me some more information about the commands you were running? You must build the image locally prior to running it.

**Comment by somedevreally** [comment]
oh ok, my bad

**Comment by dstubbs95** [comment]
I have added a docker hub for it. This way you can pull the image and use it without having to worry about building it. https://hub.docker.com/r/dstubbs95/docker-youtube-dlg

**Comment by somedevreally** [comment]
thanks for the container, i get this error when downloading

```[Tue Jan  7 22:50:59 2020] WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
[Tue Jan  7 22:50:59 2020] WARNING: Unable to extract video title
[Tue Jan  7 22:50:59 2020] WARNING: unable to extract description; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[Tue Jan  7 22:50:59 2020] ERROR: This video is restricted. Try signing in with a G Suite account.
[Tue Jan  7 22:50:59 2020] Sorry about that.``

**Comment by dstubbs95** [comment]
Based on the error message, it seems this error is with the actual youtube-dl application, not with the youtube-dlg GUI interface. You can try from the settings button in the upper right hand corner to select update. This will attempt to update the youtube-dl version used. The error suggest that perhaps the video requires being signed in to a G Suite account. If this is the case, then youtube-dl will not work.
