### ISSUE TITLE
Volume owner issue

### ISSUE THREAD

**Issue by keremcankabadayi** [dstubbs95/docker-youtube-dlg#2]
Hi there, I have a issue about volume owner.

creating container `docker run --name youtube-dl -d -p 5800:5800 -v /home/docker/deluge/downloads/web-downloads:/youtube-dl-downloads dstubbs95/docker-youtube-dlg:latest`

![image](https://user-images.githubusercontent.com/23381187/82908271-6d78ac80-9f70-11ea-883a-1bc37c84a411.png)
As you see owner of my folder is `ubuntu` but my current user is `kerem`
when I change the owner with `sudo chown -R kerem:kerem web-downloads/` downloader stucks at `Pre Proccessing` I need to create volume owner as current user `kerem`.

Maybe this is docker issue or different issue. I couldnt find to work around for this. What am i missing here, any idea?

**Comment by dstubbs95** [comment]
Hmm this is a permissions issue. In order for the docker container to be able to write into the `/home/docker/deluge/downloads/web-downloads` directory, the `ubuntu` user must have write access. There are two ways around this. 

The preferred solution would probably be to set the user in the Docker container `ubuntu` to match the user id of your local user `kerem`. When logged in as `kerem`, type `id` in the terminal and you will be able to see the UID of your current user. This is typically 1000 or some number close to that. From there, you can use this information to change the UID and GID that the user in the docker container runs as by passing the `USER_ID` and `GROUP_ID` environment variables to docker via the `-e` flag. For example: If my UID is `1001`, then I would start the docker container via a command like `docker run --name youtube-dl -d -p 5800:5800 -e USER_ID=1001 -e GROUP_ID=1001 -v ...`. See more on this issue on the README from the container this is based on: [https://github.com/jlesage/docker-baseimage-gui#usergroup-ids](https://github.com/jlesage/docker-baseimage-gui#usergroup-ids)

The second would be to change the owner of your web-downloads directory to "kerem" and the group to "ubuntu" then set the permissions as 775 which would allow the user "karem" and any users in the group ubuntu "rwx" access and everyone else "rw" access. The could be accoplished with two commands: 
`chown -R kerem:ubuntu web-downloads/` then `chmod -R 775 web-downloads/`

I think that should fix the issue, but let me know if it does not.

**Comment by keremcankabadayi** [comment]
Preferred solution worked. Actually i tried with `--user 1001:1002`, it didnt work. `-e USER_ID=1001 -e GROUP_ID=1002` did work. Thanks.
